import streamlit as st
import pandas as pd
import re
import io
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formataddr
from email import encoders
from openpyxl.styles import Alignment, PatternFill, Border, Side

# --- EMAIL CONFIGURATION ---
SENDER_EMAIL = "atharvaujoshi@gmail.com"
SENDER_NAME = "Spydarr Market Research" 
APP_PASSWORD = "nybl zsnx zvdw edqr"

# --- AUTHORIZED USERS LIST ---
# Add the known prefixes of your team here to prevent "Ghost" sends
AUTHORIZED_USERS = ["atharva.joshi", "admin", "test.user"] 

def send_email(recipient_email, excel_data, filename):
    try:
        recipient_name = recipient_email.split('@')[0].replace('.', ' ').title()
        msg = MIMEMultipart()
        msg['From'] = formataddr((SENDER_NAME, SENDER_EMAIL))
        msg['To'] = recipient_email
        msg['Subject'] = "Spydarr Market Research Summary"

        body = f"""Dear {recipient_name},
        
Please find the attached professional property analysis report generated by the dashboard.

The report includes:
1. Raw Data with calculated APR and Configurations.
2. A summarized view of APR statistics across properties.

Regards,
Atharva Joshi"""
        
        msg.attach(MIMEText(body, 'plain'))
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(excel_data)
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', f"attachment; filename= {filename}")
        msg.attach(part)

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        
        # This will fail if the recipient is invalid according to the mail server
        server.send_message(msg)
        server.quit()
        return True, "Success"
    except smtplib.SMTPRecipientsRefused:
        return False, "The recipient address was rejected."
    except Exception as e:
        return False, str(e)

# ... (Previous extraction logic remains the same) ...

# --- STREAMLIT UI ---
st.set_page_config(page_title="Spydarr Dashboard", layout="wide")
st.title("Spydarr Dashboard")

# UI Note section
st.markdown("""
    <div style='margin-top: -15px; margin-bottom: 10px;'>
        <span style='background-color: #FFFF00; padding: 2px 8px; border-radius: 4px; border: 1px solid #E6E600; font-size: 0.9em; color: black;'>
            <u><strong>NOTE :-</strong> Please cross-check the report manually.</u>
        </span>
    </div>
    """, unsafe_allow_html=True)
st.divider()

# (Assuming file upload and calculation logic is here)
# ...

if 'summary' in locals():
    st.subheader("📩 Share Report")
    c1, c2 = st.columns([2, 1])
    with c1:
        # Key="email" helps trigger browser autofill
        raw_input = st.text_input("Recipient Email ID", placeholder="firstname.lastname", key="email")
        clean_id = raw_input.split('@')[0].strip().lower()
    with c2:
        st.markdown("<div style='padding-top: 32px; font-weight: bold; color: #555;'>@beyondwalls.com</div>", unsafe_allow_html=True)
    
    full_email = f"{clean_id}@beyondwalls.com"
    
    if st.button("Send to Email"):
        if clean_id:
            # 1. OPTIONAL: Check against a list of known employees
            # if clean_id not in AUTHORIZED_USERS:
            #     st.error("User not found in organization. Please check the email ID again.")
            
            # 2. Syntax Check
            if not re.match(r"^[a-z0-9.]+$", clean_id):
                st.error("Invalid characters detected. Please check the email ID again.")
            else:
                with st.spinner(f"Validating and sending to {full_email}..."):
                    success, message = send_email(full_email, output.getvalue(), "Spydarr_Report.xlsx")
                    if success:
                        st.success(f"Report successfully sent to {full_email}!")
                        st.balloons()
                    else:
                        # This error message is triggered if the email doesn't exist
                        st.error(f"Failed to send. Please check the email ID again.")
        else:
            st.warning("Please enter a name.")
