"""
Spydarr Dashboard (rebuilt)
---------------------------
Upload a raw registration export (.csv or .xlsx). If the file is an .xlsx
workbook, the sheet named "in" is read (case-insensitive match; falls back
to the first sheet if no sheet is named "in"). CSVs are read as-is.

Core logic (all written from scratch):
1. Resolve "Area Type" per row -> 'carpet' / 'usable_carpet' / '' (blank).
   Blank cells are filled with the most frequently occurring non-blank
   Area Type for that Property (mode). Existing non-blank values are
   never touched.
2. The "Area" column is treated as already being in SQ.FT.
3. If (and only if) the resolved Area Type for a row is exactly 'carpet'
   (not usable/useable carpet), the Property Description is scanned for
   balcony / enclosed / open / utility / terrace components (Marathi /
   Hindi / English, in sq.mt or sq.ft) and their sq.ft-equivalent is
   ADDED on top of the Area column value. Parking and other non-livable
   mentions are excluded.
4. Final Carpet Area (SQ.FT) = Area [+ additional components if 'carpet'].
   Carpet Area (SQ.MT) = Carpet Area (SQ.FT) / 10.764.
   Saleable Area = Carpet Area (SQ.FT) * Loading Factor (user input).
   APR = Consideration Value / Saleable Area.
   Configuration = derived from user-supplied 1/2/3 BHK sq.ft thresholds;
   anything at/above the 3 BHK threshold is '4 BHK'.
5. Output workbook: 'Raw Data' (original + 5 new columns appended at the
   very end) and 'Summary' (grouped stats per Location/Property/Config).

Email sending logic and BHK-threshold-driven Configuration logic are
carried over conceptually from the earlier dashboard; everything else
(area extraction, area-type resolution, aggregation, formatting) is
built fresh for this spec.
"""

import io
import re
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr

import pandas as pd
import streamlit as st
from openpyxl.styles import Alignment, Border, PatternFill, Side

# =========================================================================
# EMAIL CONFIGURATION
# =========================================================================
# Prefer Streamlit secrets if configured (st.secrets["EMAIL_SENDER"] etc.),
# otherwise fall back to these defaults. Keeping credentials in st.secrets
# is strongly recommended over hardcoding them in source.
try:
    SENDER_EMAIL = st.secrets.get("EMAIL_SENDER", "atharvaujoshi@gmail.com")
    APP_PASSWORD = st.secrets.get("EMAIL_APP_PASSWORD", "nybl zsnx zvdw edqr")
except Exception:
    SENDER_EMAIL = "atharvaujoshi@gmail.com"
    APP_PASSWORD = "nybl zsnx zvdw edqr"
SENDER_NAME = "Spydarr Market Research"


def send_email(recipient_email, excel_bytes, filename):
    """Send the generated workbook as an email attachment."""
    try:
        recipient_name = recipient_email.split("@")[0].replace(".", " ").title()
        msg = MIMEMultipart()
        msg["From"] = formataddr((SENDER_NAME, SENDER_EMAIL))
        msg["To"] = recipient_email
        msg["Subject"] = "Spydarr Market Research Summary"

        body = f"""Dear {recipient_name},

Please find attached the property analysis report generated by the dashboard.

The report includes:
1. Raw Data with calculated Carpet Area, Saleable Area, APR and Configuration.
2. A summarized view of APR statistics across properties.

Regards,
Atharva Joshi"""
        msg.attach(MIMEText(body, "plain"))

        part = MIMEBase("application", "octet-stream")
        part.set_payload(excel_bytes)
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        st.error(f"Error sending email: {e}")
        return False


# =========================================================================
# AREA-TYPE RESOLUTION
# =========================================================================
def normalize_area_type(val):
    """Map a raw Area Type cell to 'carpet' / 'usable_carpet' / '' (blank)."""
    if pd.isna(val):
        return ""
    s = re.sub(r"\s+", " ", str(val).strip().lower())
    if s == "":
        return ""
    if "usable" in s or "useable" in s:
        return "usable_carpet"
    if "carpet" in s:
        return "carpet"
    return ""


def resolve_area_types(df, area_type_col, property_col):
    """
    Return a Series aligned to df.index with resolved area types
    ('carpet' / 'usable_carpet' / ''). Blank cells are filled with the
    most frequently occurring non-blank Area Type for that Property.
    """
    normalized = df[area_type_col].apply(normalize_area_type)

    helper = pd.DataFrame({"prop": df[property_col], "norm": normalized})
    non_blank = helper[helper["norm"] != ""]

    if len(non_blank) > 0:
        mode_per_property = (
            non_blank.groupby("prop")["norm"]
            .agg(lambda s: s.value_counts().idxmax())
            .to_dict()
        )
    else:
        mode_per_property = {}

    resolved = normalized.copy()
    blank_mask = resolved == ""
    resolved.loc[blank_mask] = df.loc[blank_mask, property_col].map(mode_per_property).fillna("")
    return resolved


# =========================================================================
# ADDITIONAL AREA (BALCONY / UTILITY / TERRACE / ENCLOSED / OPEN) EXTRACTION
# =========================================================================
M_UNIT = (
    r"(?:चौरस\s*मी(?:[टत]र)?|चौ[\.\s]*मी[\.\s]*|चाै[\.\s]*मी[\.\s]*"
    r"|sq\.?\s*m(?:tr)?\.?|square\s*meter(?:s)?)"
)
F_UNIT = (
    r"(?:चौरस\s*फु[टत]|चौरस\s*फू[टत]|चौ[\.\s]*फु[टत]?|चौ[\.\s]*फू[टत]?"
    r"|sq\.?\s*f(?:t)?\.?|square\s*f(?:ee|oo)t)"
)

# Words that, if found just before a matched number+unit, indicate that
# number is a balcony / utility / terrace / enclosed / open component.
COMPONENT_KEYWORDS = [
    "बाल्कनी", "balcony", "इन्क्लोज्ड", "क्लोज्ड", "बंदिस्त",
    "ओपन", "open", "enclosed", "लगतच", "युटिलिटी", "utility",
    "टेरेस", "terrace", "ड्राय", "dry", "अटॅच",
]

# Words that, if found just before a matched number+unit, mean that number
# should be excluded entirely (parking, land/plot stats, reserved area, etc).
EXCLUDE_KEYWORDS = [
    "पार्किंग", "पार्कींग", "parking", "road", "reserve", "राखीव",
    "प्लॉट", "plot", "वाढीव", "पैकी", "अविभक्त", "साईज", "size",
    "बिल्डअप", "मुल्यांकन", "दर", "rate", "७/१२", "नाकाश",
]

CONTEXT_WINDOW = 45  # characters looked at before a matched number

# Descriptions frequently restate the SAME figure in both units, e.g.
# "13.34 चौ.मी. म्हणजेच 143 चौ.फुट" ("i.e. 143 sq.ft"). Without stripping
# the restatement, both numbers would be picked up and summed, doubling
# that component. This removes the "म्हणजेच <value> <unit>" restatement,
# keeping only the first-stated figure.



_DEDUP_RESTATEMENT = re.compile(
    rf"म्हणजे[च]?\s*\d+\.?\d*\s*(?:{M_UNIT}|{F_UNIT})", re.IGNORECASE
)


def _clean_text(text):
    text = " ".join(str(text).split())
    text = re.sub(r"(\d+)\s*\.\s*(\d+)", r"\1.\2", text)   # fix "12 . 5" -> "12.5"
    text = re.sub(r"(\d),(\d)", r"\1\2", text)             # fix "1,250" -> "1250"
    text = _DEDUP_RESTATEMENT.sub("", text)                # drop unit-restatement duplicates
    return text


def extract_additional_area_sqft(description):
    """
    Scan the (Marathi/Hindi/English) Property Description for balcony /
    enclosed / open / utility / terrace figures given in sq.mt and/or
    sq.ft, and return their SUM converted to sq.ft. Parking-dimension
    patterns (e.g. '2.25 मी. X 4.5 मी.') and excluded-keyword numbers are
    skipped.
    """
    if pd.isna(description) or str(description).strip() == "":
        return 0.0

    text = _clean_text(description)
    # neutralise parking-style "A x B" dimension strings so they can't be
    # mistaken for a standalone area figure
    text = re.sub(r"\d+\.?\d*\s*[xX\*]\s*\d+\.?\d*", "DIM", text)

    total_sqft = 0.0
    for unit_pattern, is_metric in [(M_UNIT, True), (F_UNIT, False)]:
        for match in re.finditer(rf"(\d+\.?\d*)\s?{unit_pattern}", text, re.IGNORECASE):
            value = float(match.group(1))
            context_before = text[max(0, match.start() - CONTEXT_WINDOW):match.start()].lower()

            if any(kw.lower() in context_before for kw in EXCLUDE_KEYWORDS):
                continue
            if any(kw.lower() in context_before for kw in COMPONENT_KEYWORDS):
                total_sqft += value * 10.764 if is_metric else value

    return round(total_sqft, 3)


# =========================================================================
# CONFIGURATION (BHK) DERIVATION
# =========================================================================
def determine_config(carpet_sqft, t1, t2, t3):
    if carpet_sqft <= 0:
        return "N/A"
    if carpet_sqft < t1:
        return "1 BHK"
    elif carpet_sqft < t2:
        return "2 BHK"
    elif carpet_sqft < t3:
        return "3 BHK"
    else:
        return "4 BHK"


# =========================================================================
# EXCEL FORMATTING
# =========================================================================
BAND_COLORS = ["A2D2FF", "FFD6A5", "CAFFBF", "FDFFB6", "FFADAD", "BDB2FF", "9BF6FF"]


def write_formatted_sheet(df, writer, sheet_name, band_columns=None):
    """
    Write df to sheet_name with a frozen header row, centered/wrapped text,
    and (if band_columns is given) alternating background bands + merged
    cells whenever the value in band_columns[0]/[1] changes, mirroring how
    the Summary sheet groups rows visually by Location / Property.
    """
    df.to_excel(writer, sheet_name=sheet_name, index=False)
    ws = writer.sheets[sheet_name]
    ws.freeze_panes = "A2"

    center = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin = Side(style="thin")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    n_rows, n_cols = ws.max_row, ws.max_column
    for r in range(1, n_rows + 1):
        for c in range(1, n_cols + 1):
            cell = ws.cell(row=r, column=c)
            cell.alignment = center
            if band_columns:
                cell.border = border

    if not band_columns:
        return

    last_col = n_cols

    def cell_val(row_idx_0based, col_idx_0based):
        return df.iloc[row_idx_0based, col_idx_0based] if 0 <= row_idx_0based < len(df) else None

    color_i = 0
    prop_start = 2
    loc_start = 2
    for excel_row in range(2, len(df) + 3):
        i0 = excel_row - 2  # 0-based row index into df for this excel row
        curr_prop = cell_val(i0, 1)
        prev_prop = cell_val(i0 - 1, 1)
        curr_loc = cell_val(i0, 0)
        prev_loc = cell_val(i0 - 1, 0)

        if curr_prop != prev_prop and excel_row > 2:
            fill = PatternFill(start_color=BAND_COLORS[color_i % len(BAND_COLORS)],
                                end_color=BAND_COLORS[color_i % len(BAND_COLORS)],
                                fill_type="solid")
            for r in range(prop_start, excel_row):
                for c in range(2, last_col + 1):
                    ws.cell(row=r, column=c).fill = fill
            if excel_row - 1 > prop_start:
                ws.merge_cells(start_row=prop_start, start_column=2, end_row=excel_row - 1, end_column=2)
            prop_start = excel_row
            color_i += 1

        if curr_loc != prev_loc and excel_row > 2:
            if excel_row - 1 > loc_start:
                ws.merge_cells(start_row=loc_start, start_column=1, end_row=excel_row - 1, end_column=1)
            loc_start = excel_row


# =========================================================================
# STREAMLIT UI
# =========================================================================
st.set_page_config(page_title="Spydarr Dashboard", layout="wide")
st.title("Spydarr Dashboard")
st.markdown(
    "<div style='margin-top:-10px;margin-bottom:5px;'>"
    "<span style='background-color:#FFFF00;padding:2px 8px;border-radius:4px;"
    "border:1px solid #E6E600;font-size:0.9em;color:black;'>"
    "<u><strong>NOTE:</strong> Please cross-check the report manually.</u></span></div>",
    unsafe_allow_html=True,
)
st.divider()

uploaded_file = st.file_uploader("Upload Data File", type=["xlsx", "csv"])

if uploaded_file:
    # --- Load the data, preferring a sheet literally/loosely named "in" ---
    if uploaded_file.name.lower().endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        xls = pd.ExcelFile(uploaded_file)
        target_sheet = next((s for s in xls.sheet_names if s.strip().lower() == "in"), None)
        if target_sheet is None:
            target_sheet = xls.sheet_names[0]
            st.info(f"No sheet named 'in' found — using sheet '{target_sheet}' instead.")
        df = pd.read_excel(xls, sheet_name=target_sheet)

    clean_cols = {c.lower().strip(): c for c in df.columns}
    area_col = clean_cols.get("area")
    area_type_col = clean_cols.get("area type")
    prop_col = clean_cols.get("property")
    desc_col = clean_cols.get("property description")
    cons_col = clean_cols.get("consideration value")
    loc_col = clean_cols.get("micromarket")
    date_col = clean_cols.get("completion date")

    required = {"Area": area_col, "Area Type": area_type_col, "Property": prop_col,
                "Property Description": desc_col, "Consideration Value": cons_col,
                "Micromarket": loc_col}
    missing = [name for name, col in required.items() if col is None]

    if missing:
        st.error(f"Missing required column(s): {', '.join(missing)}")
    else:
        st.sidebar.header("BHK Thresholds (Carpet Area, SQ.FT)")
        t1 = st.sidebar.number_input("1 BHK Threshold (< )", value=600)
        t2 = st.sidebar.number_input("2 BHK Threshold (< )", value=850)
        t3 = st.sidebar.number_input("3 BHK Threshold (< , else 4 BHK)", value=1100)
        loading_factor = st.sidebar.number_input(
            "Loading Factor", min_value=1.0, value=1.35, step=0.001, format="%.3f"
        )

        with st.spinner("Calculating..."):
            df[area_col] = pd.to_numeric(df[area_col], errors="coerce").fillna(0.0)
            df[cons_col] = pd.to_numeric(df[cons_col], errors="coerce").fillna(0.0)

            resolved_type = resolve_area_types(df, area_type_col, prop_col)

            additional_sqft = df[desc_col].apply(extract_additional_area_sqft)
            # Only ADD the balcony/utility/etc. components when the resolved
            # Area Type is exactly 'carpet' (not usable/useable carpet, not blank)
            additional_sqft = additional_sqft.where(resolved_type == "carpet", 0.0)

            carpet_sqft = (df[area_col] + additional_sqft).round(3)

            df["Carpet Area (SQ.MT)"] = (carpet_sqft / 10.764).round(3)
            df["Carpet Area (SQ.FT)"] = carpet_sqft
            df["Saleable Area"] = (carpet_sqft * loading_factor).round(3)
            df["APR"] = df.apply(
                lambda r: round(r[cons_col] / r["Saleable Area"], 3) if r["Saleable Area"] > 0 else 0,
                axis=1,
            )
            df["Configuration"] = carpet_sqft.apply(lambda x: determine_config(x, t1, t2, t3))

            if date_col:
                df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

            valid = df[df["Carpet Area (SQ.FT)"] > 0].copy()
            sort_cols = [loc_col, prop_col, "Configuration", "Carpet Area (SQ.FT)"]
            valid = valid.sort_values(sort_cols)

            total_count = valid.groupby(prop_col).size().reset_index(name="Total Count")

            agg_dict = {
                "Min. APR": ("APR", "min"),
                "Max APR": ("APR", "max"),
                "Average of APR": ("APR", "mean"),
                "Median of APR": ("APR", "median"),
                "Count of Property": (prop_col, "count"),
            }
            if date_col:
                agg_dict["Last Completion Date"] = (date_col, "max")

            summary = (
                valid.groupby([loc_col, prop_col, "Configuration", "Carpet Area (SQ.FT)"])
                .agg(**agg_dict)
                .reset_index()
            )
            summary = summary.merge(total_count, on=prop_col, how="left")

            if date_col:
                summary["Last Completion Date"] = pd.to_datetime(
                    summary["Last Completion Date"], errors="coerce"
                ).apply(lambda x: x.strftime("%b-%Y") if pd.notnull(x) else "N/A")

            rename_map = {loc_col: "Location", prop_col: "Property",
                          "Carpet Area (SQ.FT)": "Carpet Area(SQ.FT)"}
            summary = summary.rename(columns=rename_map)

            ordered_cols = ["Location", "Property"]
            if date_col:
                ordered_cols.append("Last Completion Date")
            ordered_cols += ["Configuration", "Carpet Area(SQ.FT)", "Min. APR", "Max APR",
                              "Average of APR", "Median of APR", "Count of Property", "Total Count"]
            summary = summary[ordered_cols]

            output = io.BytesIO()
            with pd.ExcelWriter(output, engine="openpyxl") as writer:
                write_formatted_sheet(df, writer, "Raw Data", band_columns=None)
                write_formatted_sheet(summary, writer, "Summary", band_columns=["Location", "Property"])

        st.success("Analysis Complete!")
        st.dataframe(summary, use_container_width=True)


        st.divider()
        recipient = st.text_input("Recipient Name", placeholder="firstname.lastname")
        if st.button("Send to Email") and recipient:
            full_email = f"{recipient.strip().lower()}@beyondwalls.com"
            if send_email(full_email, output.getvalue(), "Spydarr_Market_Report.xlsx"):
                st.success(f"Report sent to {full_email}")
